# Generated by Django 3.0.6 on 2021-05-02 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assyster_app', '0008_test_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='course_id',
        ),
        migrations.AddField(
            model_name='test',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assyster_app.Subjects'),
        ),
    ]
