# Generated by Django 3.0.6 on 2021-05-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assyster_app', '0009_auto_20210502_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
