# Generated by Django 3.0.6 on 2021-05-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assyster_app', '0010_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assyster_app.Staffs')),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assyster_app.Subjects')),
            ],
        ),
    ]
