# Generated by Django 3.0.6 on 2021-05-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assyster_app', '0011_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_exam_marks',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='marks',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
