# Generated by Django 3.0.6 on 2021-05-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assyster_app', '0012_auto_20210502_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='test_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assyster_app.Tests'),
        ),
    ]
