# Generated by Django 3.0.6 on 2021-05-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assyster_app', '0013_studentresult_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='test_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assyster_app.Tests'),
        ),
    ]
