# Generated by Django 3.0.6 on 2021-05-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assyster_app', '0014_auto_20210502_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
