# Generated by Django 3.0.6 on 2021-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assyster_app', '0015_auto_20210515_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
